name: SpeedrunStats
version: '${project.version}'
main: dev.osowiz.speedrunstats.SpeedrunStats
api-version: '1.20'
load: STARTUP
authors: [OsoWiz]
description: Plugin for speedrunning in teams

commands:
  start:
    description: Start a speedrun
    usage: /<command> <category>
  points:
    description: Tells the number of points you have
    usage: /<command>
    aliases: [score, getpoints, getscore]
  stats:
    description: Tells the stats of a player sending the command.
    usage: /<command>
    aliases: [statistics, getstats, getstatistics]
  config:
    description: Configures the speedrun ahead.
    usage: /<command>
    aliases: [ conf, setup, konffi ]
  rank:
    description: Tells the player their rank and what contributed to it.
    usage: /<command>
    aliases: [rankki, calculaterank ]
  listranks:
    description: Lists the ranks of the server.
    usage: /<command>
    aliases: [ranks, listaarankit, getranks]
  leaders:
    description: Lists top players on various statistics.
    usage: /<command>
    aliases: [leaderboard, topdogs, bossit]
